version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.12

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y xxd reuse
      - run: make
      - run: make check
      - run: reuse lint
